// NOLINTBEGIN(*-include-cleaner, *-env33-c)

#include "Costanti.hpp"
#ifdef _WIN32
#include <windows.h>
#endif
DISABLE_WARNINGS_PUSH(
    4005 4201 4459 4514 4625 4626 4820 6244 6285 6385 6386 26408 26409 26415 26418 26426 26429 26432 26437 26438 26440 26446 26447 26450 26451 26455 26457 26459 26460 26461 26462 26467 26472 26473 26474 26475 26481 26482 26485 26490 26491 26493 26494 26495 26496 26497 26498 26800 26814 26818 26821 26826 26827)
#include <CLI/CLI.hpp>
#include <iostream>
#include <string>

DISABLE_WARNINGS_POP()
namespace vnd {
    // NOLINTNEXTLINE(*-use-anonymous-namespace)
    static auto timeTokenizer(Tokenizer &tokenizer, std::vector<TokenVec> &tokens) -> void {
        tokens.clear();
#ifdef INDEPT
        const AutoTimer timer("tokenization");
#endif
        tokens = tokenizer.tokenize();
    }
    // NOLINTNEXTLINE(*-use-anonymous-namespace)
    void count_total_num_tokens(const std::vector<vnd::TokenVec> &tokens) {
        vnd::AutoTimer const timer("Counting total number of tokens");
        const std::size_t totalTokenSize = std::accumulate(tokens.begin(), tokens.end(), std::size_t{0},
                                                           [](std::size_t sum, const vnd::TokenVec &inner) { return sum + inner.size(); });
        LINFO("num tokens {}", totalTokenSize);
    }

}  // namespace vnd

DISABLE_WARNINGS_PUSH(26461 26821)

// static inline constexpr auto sequence = std::views::iota(0, 9999);
// NOLINTNEXTLINE(*-function-cognitive-complexity)
auto main(int argc, const char *const argv[]) -> int {
    // NOLINTNEXTLINE
    INIT_LOG()
#ifdef _WIN32
    // Set UTF-8 code page for Windows console
    SetConsoleOutputCP(CP_UTF8);

    // Optional: enable virtual terminal processing for better Unicode/emoji support
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    DWORD dwMode = 0;
    GetConsoleMode(hOut, &dwMode);
    dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
    SetConsoleMode(hOut, dwMode);
#endif
    try {
        CLI::App app{FORMAT("{} version {}", Vandior::cmake::project_name, Vandior::cmake::project_version)};  // NOLINT(*-include-cleaner)
        // std::optional<std::string> message;  // NOLINT(*-include-cleaner)
        std::optional<std::string> path;
        // app.add_option("-m,--message", message, "A message to print back out");
        app.add_option("-i,--input", path, "The input file");
        bool show_version = false;
        bool compile = false;
        bool run = false;
        bool clean = false;
        bool create_cmake = false;
        app.add_flag("--version, -v", show_version, "Show version information");
        app.add_flag("--compile, -c", compile, "Compile the resulting code");
        app.add_flag("--run, -r", run, "Compile the resulting code and execute it");
        app.add_flag("--clean, -x", clean, "Clean before building");
        app.add_flag("--cmake, -m", create_cmake, "Create a CMakeLists.txt file");
        CLI11_PARSE(app, argc, argv)
        if(show_version) {
            LINFO("{}", Vandior::cmake::project_version);
            return EXIT_SUCCESS;
        }
        const auto porfilename = fs::canonical(fs::path(path.value_or(filename.data())).lexically_normal()).string();
        if(clean) {
            const auto folderPath = vnd::GetBuildFolder(fs::path(porfilename));
            LINFO("Cleaning the project");
#ifdef INDEPT
            const vnd::Timer timer("Cleaning of the project");
#endif
            auto folderDeleted = vnd::FolderDeletionResult::deleteFolder(folderPath);
#ifdef INDEPT
            const auto folder_delition_time = timer.to_string();
#endif
            if(folderDeleted.success()) {
#ifdef INDEPT
                LINFO(folder_delition_time);
#else

                LINFO("Cleaning of the project done");
#endif
            }
        }
        const auto str = vnd::readFromFile(porfilename);
        const std::string_view code(str);
        vnd::Tokenizer tokenizer{code, porfilename};
        std::vector<vnd::TokenVec> tokens;
        vnd::timeTokenizer(tokenizer, tokens);
        LINFO("num tokens {}", tokens.size());
        LINFO("Input:\n{}", code);
        vnd::Parser parser{code, "input.vn"};
        for(const auto progrmamAST = vnd::timeParse(parser); const auto &statement : progrmamAST) {
            const auto &node = statement.get_root();
            const auto &token = statement.get_token();
            if(token.getType() == vnd::TokenType::UNKNOWN) { LINFO("the statement is not generated by any token"); }
            if(node != nullptr) {
                LINFO("{}", token);
                prettyPrint(*node);
            } else {
                LINFO("EMPTY STATMENT generated from {}", token.compat_to_string());
            }
        }
        vnd::Transpiler transpiler{code, porfilename, create_cmake};
        LINFO("transpiled code: \n{}", transpiler.transpile());
    } catch(const std::exception &e) {
        // Handle any other types of exceptions
        LERROR("Unhandled exception in main: {}", e.what());
    } catch(...) {
        // Handle any other types of exceptions
        LERROR("An unknown error occurred while creating the folder.");
    }
    return EXIT_SUCCESS;  // Return appropriate exit code
}

DISABLE_WARNINGS_POP()
// NOLINTEND(*-include-cleaner, *-env33-c)
