name: auto-clang-format
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.5
      with:
        ref: main # Ensure to checkout the main branch

    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.17
      with:
        source: '.'
        exclude: './third_party ./external'
        extensions: 'h,cpp,hpp'
        clangFormatVersion: 17
        inplace: True

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9.1.4
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: ':art: Committing clang-format changes'
        add: .
        cwd: .
        default_author: github_actor
        fetch: --tags --force
        pathspec_error_handling: ignore
        push: true
        branch: main # Specify the branch to push changes to
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
