name: auto-clang-format

on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0
      with:
        ref: ${{ github.head_ref || github.ref }} # For pull_request and other events

    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: '.'
        exclude: './third_party ./external'
        extensions: 'h,cpp,hpp'
        clangFormatVersion: 17
        inplace: true

    - name: Commit changes
      uses: EndBug/add-and-commit@v9.1.4
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: ':art: Committing clang-format changes'
        push: true
        default_author: github_actor
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
